# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-07 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daily',
            options={'ordering': ('-updated', 'title')},
        ),
        migrations.AddField(
            model_name='daily',
            name='share',
            field=models.BooleanField(default=True),
        ),
    ]
